[[ActorsOnScreen]]
name = "Skybox"
position = [0.0,0.0,0.0]
rotation = [-0.0,0.0,1.0,-0.0]
euler = [-90.0,0.0,0.0]
scale = [500.0,500.0,500.0]
path = "/Data/Primitives/Cube.glb"
type = "Terrian"
typeName = "Skybox"
domain = "Surface"
shader = "Skybox"
controller = "None"

[[ActorsOnScreen]]
name = "Rec1"
position = [5.0,5.0,8.0]
rotation = [-0.0,-0.0,1.0,-0.0]
euler = [0.0,0.0,0.0]
scale = [5.0,5.0,5.0]
path = "/Data/Primitives/Rectangle_26D5A087.glb"
type = "Terrian"
typeName = "PBR"
domain = "Surface"
shader = "PBR"
controller = "None"

[[ActorsOnScreen]]
name = "Rec2"
position = [10.0,5.0,8.0]
rotation = [-0.0,-0.0,1.0,-0.0]
euler = [0.0,0.0,0.0]
scale = [5.0,5.0,5.0]
path = "/Data/Primitives/Rectangle_78B2A5CA.glb"
type = "Terrian"
typeName = "PBR"
domain = "Surface"
shader = "PBRIBL"
controller = "None"

[[ActorsOnScreen]]
name = "Rec3"
position = [15.0,5.0,8.0]
rotation = [-0.0,-0.0,1.0,-0.0]
euler = [0.0,0.0,0.0]
scale = [5.0,5.0,5.0]
path = "/Data/Primitives/Rectangle_09547FE1.glb"
type = "Terrian"
typeName = "PBR"
domain = "Surface"
shader = "PBR"
controller = "None"