[[ActorsOnScreen]]
name = "Terrain"
position = [0.0,-150.0,0.0]
rotation = [-0.0,-0.0,1.0,-0.0]
euler = [0.0,0.0,0.0]
scale = [1000.0,1000.0,1000.0]
path = "/Data/Primitives/NewTerr.glb"
type = "Terrian"
typeName = "Basic"
domain = "Surface"
shader = "Phong"
controller = "None"

[[ActorsOnScreen]]
name = "SkyDome"
position = [0.0,-200.0,0.0]
rotation = [-0.0,-0.0,1.0,-0.0]
euler = [0.0,3.1,0.0]
scale = [750.0,750.0,750.0]
path = "/Data/Primitives/NaraSkyDome.glb"
type = "Terrian"
typeName = "Simple"
domain = "Surface"
shader = "Flat"
controller = "None"

[[ActorsOnScreen]]
name = "Chara"
position = [0.0,10.0,-30.0]
rotation = [-0.0,-0.0,1.0,-0.0]
euler = [0.0,0.0,0.0]
scale = [50.0,50.0,50.0]
path = "/Data/Primitives/Chara.glb"
type = "Terrian"
typeName = "PBR"
domain = "Surface"
shader = "PBRIBL"
controller = "None"

[[ActorsOnScreen]]
name = "Temple"
position = [-30.0,-27.0,-80.0]
rotation = [-0.0,-0.0,1.0,-0.0]
euler = [0.0,0.0,0.0]
scale = [1.0,1.0,1.0]
path = "/Data/Primitives/Temple.glb"
type = "Terrian"
typeName = "PBR"
domain = "Surface"
shader = "PBRIBL"
controller = "None"