[[ActorsOnScreen]]
name = "Skybox"
position = [0.0,0.0,0.0]
rotation = [-0.0,0.0,1.0,-0.0]
euler = [-90.0,0.0,0.0]
scale = [500.0,500.0,500.0]
path = "/Data/Primitives/Cube.glb"
type = "Terrian"
typeName = "Skybox"
domain = "Surface"
shader = "Skybox"
controller = "None"

[[ActorsOnScreen]]
name = "Water"
position = [0.0,1.3,0.0]
rotation = [-0.0,0.0,1.0,-0.0]
euler = [0.0,0.0,0.0]
scale = [15.0,15.0,15.0]
path = "/Data/Primitives/Water.glb"
type = "Terrian"
typeName = "Basic"
domain = "Surface"
shader = "Water"
controller = "None"

[[ActorsOnScreen]]
name = "Fireball"
position = [10.0,10.0, 0.0]
rotation = [-0.0,-0.0,1.0,-0.0]
euler = [90.0,0.0,0.0]
scale = [0.5,0.5,0.5]
path = "/Data/Primitives/plane.glb"
type = "Terrian"
typeName = "Fireball"
domain = "Surface"
shader = "Fireball"
controller = "None"