[[ActorsOnScreen]]
name = "Skybox"
position = [0.0,0.0,0.0]
rotation = [-0.0,0.0,1.0,-0.0]
euler = [-90.0,0.0,0.0]
scale = [500.0,500.0,500.0]
path = "/Data/Primitives/Cube.glb"
type = "Terrian"
typeName = "Skybox"
domain = "Surface"
shader = "Skybox"
controller = "None"

[[ActorsOnScreen]]
name = "Water"
position = [0.0,1.3,0.0]
rotation = [-0.0,0.0,1.0,-0.0]
euler = [0.0,0.0,0.0]
scale = [15.0,15.0,15.0]
path = "/Data/Primitives/Water.glb"
type = "Terrian"
typeName = "Basic"
domain = "Surface"
shader = "Water"
controller = "None"

[[ActorsOnScreen]]
name = "Cube1"
position = [14.0,8.0,2.0]
rotation = [-0.0,0.0,1.0,-0.0]
euler = [0.0,0.0,0.0]
scale = [3.0,3.0,3.0]
path = "/Data/ToImplementModels/testCubes.glb"
type = "Terrian"
typeName = "PBR"
domain = "Surface"
shader = "Transparent"
controller = "None"

[[ActorsOnScreen]]
name = "Cube2"
position = [4.0,8.0,2.0]
rotation = [-0.0,0.0,1.0,-0.0]
euler = [0.0,0.0,0.0]
scale = [3.0,3.0,3.0]
path = "/Data/ToImplementModels/testCubes.glb"
type = "Terrian"
typeName = "Basic"
domain = "Surface"
shader = "PBRIBL"
controller = "None"